In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("final.csv", sep=",")
df.dropna(inplace=True)  #결측치제거
df = df.reset_index(drop=True) #인덱스 초기화

In [6]:
df_up = df[df['labeling'] == 'up']
df_down = df[df['labeling']== 'down']

In [8]:
df_up = df_up.reset_index(drop=True)
df_down = df_down.reset_index(drop=True)

In [9]:
ngram_list = []    #n그램을 나눠서 리스트화
for i in range(len(df_up)):
    ngram_list +=df_up['ngrams'][i].split(',')
    
    
ngram_list2 = []
for i in range(len(df_down)):
    ngram_list2 +=df_down['ngrams'][i].split(',')

In [10]:
up_ngram_df = pd.DataFrame({'count': ngram_list}) #위에서 만든 리스트를 데이터프레임으로
up_count_df = pd.DataFrame(up_ngram_df['count'].value_counts()).reset_index()

down_ngram_df = pd.DataFrame({'count': ngram_list2}) 
down_count_df = pd.DataFrame(down_ngram_df['count'].value_counts()).reset_index()

In [11]:
up_count_df.rename(columns = {'index':'ngram','count':'up_count'},inplace=True)  #컬럼명변경
down_count_df.rename(columns={'index':'ngram','count':'down_count'},inplace=True)

In [12]:
df1 =pd.merge(up_count_df,down_count_df, how='outer', on='ngram')
df2=df1.fillna(0) #결측치를 0으로

In [13]:
df2['total_count'] = (df2['up_count']+df2['down_count'])
df2

                            ngram  up_count  down_count  total_count
0                   금리/NNG;인상/NNG    4453.0      3368.0       7821.0
1                   금리/NNG;인하/NNG    2337.0      4056.0       6393.0
2                    금리/NNG;오르/VV    1531.0      1309.0       2840.0
3                   금리/NNG;상승/NNG    1347.0      1270.0       2617.0
4                   경기/NNG;회복/NNG    1342.0      1192.0       2534.0
...                           ...       ...         ...          ...
51199        판매/NNG;지표/NNG;증가/NNG       0.0         1.0          1.0
51200       특수채/NNG;공급/NNG;감소/NNG       0.0         1.0          1.0
51201  gdp/NNG;재정/NNG;지출/NNG;늘/VV       0.0         1.0          1.0
51202                대출/NNG;없애/VV       0.0         1.0          1.0
51203      침체/NNG;신용경색/NNG;우려/NNG       0.0         1.0          1.0

[51204 rows x 4 columns]

In [14]:
df3 = df2[df2['total_count'] >=15]
df3

                                     ngram  up_count  down_count  total_count
0                            금리/NNG;인상/NNG    4453.0      3368.0       7821.0
1                            금리/NNG;인하/NNG    2337.0      4056.0       6393.0
2                             금리/NNG;오르/VV    1531.0      1309.0       2840.0
3                            금리/NNG;상승/NNG    1347.0      1270.0       2617.0
4                            경기/NNG;회복/NNG    1342.0      1192.0       2534.0
...                                    ...       ...         ...          ...
37226                        도산/NNG;우려/NNG       1.0        17.0         18.0
37669              글로벌/NNG;금융위기/NNG;해소/NNG       1.0        16.0         17.0
41260                          여력/NNG;늘/VV       0.0        22.0         22.0
41261  상승률/NNG;물가/NNG;안정/NNG;목표/NNG;안정/NNG       0.0        16.0         16.0
41262               신용위기/NNG;경제/NNG;성장/NNG       0.0        15.0         15.0

[6534 rows x 4 columns]

In [218]:
print(df3['up_count'].sum(axis=0))
print(df3['down_count'].sum(axis=0))

196517.0
205222

In [15]:
#Polarity Score 구하기
df3['polar_score'] = ((df3['up_count'] / sum(df3['up_count']) )/(df3['down_count']/sum(df3['down_count'])))

<ipython-input-15-1762ca6b58be>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['polar_score'] = ((df3['up_count'] / sum(df3['up_count']) )/(df3['down_count']/sum(df3['down_count'])))

In [16]:
df3

,ngram,up_count,down_count,total_count,polar_score
0,금리/NNG;인상/NNG,4453.0,3368.0,7821.0,1.386471
1,금리/NNG;인하/NNG,2337.0,4056.0,6393.0,0.604214
2,금리/NNG;오르/VV,1531.0,1309.0,2840.0,1.226495
3,금리/NNG;상승/NNG,1347.0,1270.0,2617.0,1.112229
4,경기/NNG;회복/NNG,1342.0,1192.0,2534.0,1.180610
...,...,...,...,...,...
37226,도산/NNG;우려/NNG,1.0,17.0,18.0,0.061685
37669,글로벌/NNG;금융위기/NNG;해소/NNG,1.0,16.0,17.0,0.065541
41260,여력/NNG;늘/VV,0.0,22.0,22.0,0.000000
41261,상승률/NNG;물가/NNG;안정/NNG;목표/NNG;안정/NNG,0.0,16.0,16.0,0.000000
41262,신용위기/NNG;경제/NNG;성장/NNG,0.0,15.0,15.0,0.000000

In [17]:
def polarity(n):
    if n > 1.3:
        return 'Hawkish'
    elif n < 0.76:
        return 'Dovish'
    else:
        return 'nothing'

In [18]:
df3['polarity'] = df3['polar_score'].apply(polarity)

<ipython-input-18-1b12cf7ef46f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['polarity'] = df3['polar_score'].apply(polarity)

In [223]:
df3

,ngram,up_count,down_count,total_count,polar_score,polarity
0,금리/NNG;인상/NNG,3978.0,4345,8323.0,0.956090,nothing
1,금리/NNG;인하/NNG,3281.0,3311,6592.0,1.034834,nothing
2,경기/NNG;회복/NNG,1580.0,1677,3257.0,0.983893,nothing
3,금리/NNG;오르/VV,1404.0,1498,2902.0,0.978766,nothing
4,금리/NNG;상승/NNG,1328.0,1403,2731.0,0.988472,nothing
...,...,...,...,...,...,...
8884,재정위기/NNG;완화/NNG,6.0,9,15.0,0.696198,Dovish
8895,금리/NNG;많이/MAG;하락/NNG,6.0,9,15.0,0.696198,Dovish
9802,전세가격/NNG;안정/NNG,5.0,12,17.0,0.435124,Dovish
11660,가격/NNG;파운드/NNG;하락/NNG,4.0,11,15.0,0.379744,Dovish
12282,대출/NNG;금리/NNG;역대/NNG;최저/NNG,4.0,11,15.0,0.379744,Dovish

In [19]:
df_Neg = df3[df3['polarity'] == 'Dovish'] #부정사전 긍정사전 만들기
df_Pos = df3[df3['polarity'] == 'Hawkish']

In [20]:
df_Neg=df_Neg.sort_values('total_count',ascending=False) #정렬하기
df_Pos=df_Pos.sort_values('total_count',ascending=False)

In [21]:
df_Pos

,ngram,up_count,down_count,total_count,polar_score,polarity
0,금리/NNG;인상/NNG,4453.0,3368.0,7821.0,1.386471,Hawkish
20,물가/NNG;상승/NNG,505.0,398.0,903.0,1.330573,Hawkish
30,유가/NNG;상승/NNG,362.0,280.0,642.0,1.355754,Hawkish
35,서브프라임/NNG;부실/NNG,338.0,209.0,547.0,1.695902,Hawkish
40,인플레이션/NNG;억제/NNG,317.0,221.0,538.0,1.504171,Hawkish
...,...,...,...,...,...,...
4174,원자재/NNG;강세/NNG,11.0,4.0,15.0,2.883786,Hawkish
4136,인플레이션/NNG;금리/NNG;인상/NNG;우려/NNG,11.0,4.0,15.0,2.883786,Hawkish
4974,경제/NNG;최대/NNG;위험/NNG,9.0,6.0,15.0,1.572974,Hawkish
4981,금리/NNG;하락/NNG;막/VV,9.0,6.0,15.0,1.572974,Hawkish
4111,호조/NNG;강세/NNG,11.0,4.0,15.0,2.883786,Hawkish